#!/usr/bin/env bash

usage() {
	echo "Incorrect number of arguments."
	echo -e "\nUsage:\n$0 <dos input>"
}

if [ $# -le 0 ]
then
	usage
	exit 1
fi

if [[ ( $# == "--help") || $# == "-h" ]]
then
	usage
	exit 0
fi

#tr -d '\015' <$1 > $2.unix
tr -d '\r' <$1 > $1.unix
echo "Wrote output to $1.unix"

