#!/usr/bin/env bash

usage() {
	echo "Incorrect number of arguments."
	echo -e "\nUsage:\n$0 <unix input> <dos output>"
}

if [ $# -le 1 ]
then
	usage
	exit 1
fi

if [[ ( $# == "--help") || $# == "-h" ]]
then
	usage
	exit 0
fi

sed 's/$'"/`echo \\\r`/" $1 > $2
echo "Wrote output to $2"

